# Generated by Django 4.2.21 on 2025-05-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email du contact')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone (optionnel)')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet du message')),
                ('message', models.TextField(verbose_name='Contenu du message')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('status', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Lu', 'Lu'), ('En cours', 'En cours de traitement'), ('Résolu', 'Résolu')], default='Nouveau', max_length=20, verbose_name='Statut du message')),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-submission_date'],
            },
        ),
    ]
