# Generated by Django 4.2.21 on 2025-05-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description détaillée du service')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name="Classe d'icône (ex: 'fa-solid fa-code')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Service actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('key_points', models.TextField(blank=True, verbose_name='Points clés / Avantages (un par ligne)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
    ]
