# Generated by Django 4.2.21 on 2025-05-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la réalisation')),
                ('description', models.TextField(verbose_name='Description détaillée du projet')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du client (optionnel)')),
                ('url_link', models.URLField(blank=True, null=True, verbose_name='Lien du site réalisé')),
                ('realization_date', models.DateField(verbose_name='Date de réalisation')),
                ('technologies_used', models.CharField(blank=True, max_length=255, verbose_name='Technologies utilisées (ex: Django, React, PostgreSQL)')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Image 1 du projet')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Image 2 du projet')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Image 3 du projet')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Catégorie de service liée')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-realization_date'],
            },
        ),
    ]
